language: python
python: '2.7'
install:
- pip install codecov
- pip install coverage
script:
- python -m unittest discover -v
- coverage run Test.py
after_success:
- codecov --token=6e731c56-8707-4b85-a106-8cf19d01c6b1
deploy:
  provider: s3
  access_key_id: $awsid
  secret_access_key: $awskey
  bucket: "cps847group12"
  skip_cleanup: true
  region: ca-central-1
  local_dir: html
  
